idf_component_register(
    SRCS
        "main.c"
        "wifi_manager.c"
        "api_client.c"
        "device_manager.c"
        "display_driver.c"
        "display_ui.c"
        "audio_codecs.c"
        "config_store.c"
        "gemini_client.c"
    INCLUDE_DIRS "."
    REQUIRES
        nvs_flash
        esp_wifi
        esp_http_client
        esp-tls
        esp_lcd
        driver
        cjson
        esp_timer
        esp_driver_gpio
        esp_driver_ledc
        esp_driver_i2c
        esp_driver_i2s
        esp_websocket_client
        mbedtls
        esp_ringbuf
)
